name: Generate Xcode Project

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      uniqueId:
        required: true
        description: 'Unique identifier for this workflow run'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen generate -s project_temp.yml

    - name: Find Xcode Project File
      id: find_project
      run: |
        PROJECT_PATH=$(find . -name '*.xcodeproj' -print -quit)
        echo "PROJECT_PATH=$PROJECT_PATH" >> $GITHUB_ENV
        PROJECT_NAME=$(basename "$PROJECT_PATH")
        echo "::set-output name=project_name::$PROJECT_NAME"

    - name: Archive Project
      run: |
        ZIP_NAME="${{ steps.find_project.outputs.project_name }}-${{ github.event.inputs.uniqueId }}.zip"
        zip -r "$ZIP_NAME" "${{ env.PROJECT_PATH }}"

    - name: Upload ZIP as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: project-zip-${{ github.event.inputs.uniqueId }}
        path: ${{ steps.find_project.outputs.project_name }}-${{ github.event.inputs.uniqueId }}.zip

