name: Generate Xcode Project

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      uniqueId:
        required: true
        description: 'Unique identifier for this workflow run'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Commit Changes
        run: |
          UNIQUE_ID="${{ github.event.inputs.uniqueId }}"
          COMMIT_MESSAGE="Generated project for uniqueId: $UNIQUE_ID"
          git config --global user.name "cryptomacedonia"
          git config --global user.email "cryptomacedonia@edit8.com"
          git add .
          git commit --allow-empty -m "$COMMIT_MESSAGE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash


      - name: Push Changes
        if: success()
        run: |
          git push https://<cryptomacedonia>:${{ secrets.PAT }}@github.com/cryptomacedonia/my-github-actions-project.git
        shell: bash
      

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Find Xcode Project File
        id: find_project
        run: |
          PROJECT_PATH=$(find . -name '*.xcodeproj' -print -quit)
          echo "PROJECT_PATH=$PROJECT_PATH" >> $GITHUB_ENV
          PROJECT_NAME=$(basename "$PROJECT_PATH")
          echo "::set-output name=project_name::$PROJECT_NAME"

      - name: Archive Project
        run: |
          zip -r "${{ steps.find_project.outputs.project_name }}-${{ github.event.inputs.uniqueId }}.zip" "${{ env.PROJECT_PATH }}"

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: project-zip-${{ github.event.inputs.uniqueId }}
          path: ${{ steps.find_project.outputs.project_name }}-${{ github.event.inputs.uniqueId }}.zip
